# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Order.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymongo
import dns
from PyQt5.QtWidgets import QTableWidgetItem
import base64
import ctypes
import lib_Help
import Receipt
import webbrowser
import os

class Ui_Order(object):

    def setupUi(self, Order,Menu,Pizza):
        Order.setObjectName("Order")
        Order.setWindowModality(QtCore.Qt.NonModal)
        Order.setEnabled(True)
        Order.resize(406, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Order.sizePolicy().hasHeightForWidth())
        Order.setSizePolicy(sizePolicy)
        Order.setMinimumSize(QtCore.QSize(1, 1))
        Order.setMaximumSize(QtCore.QSize(800, 600))
        Order.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pictures/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Order.setWindowIcon(icon)
        Order.setToolTip("")
        Order.setStyleSheet("")
        Order.setModal(False)
        self.label = QtWidgets.QLabel(Order)
        self.label.setGeometry(QtCore.QRect(-50, 0, 461, 431))
        self.label.setMinimumSize(QtCore.QSize(1, 1))
        self.label.setMaximumSize(QtCore.QSize(9999, 9999))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Pictures/269 (1).jpg"))
        self.label.setObjectName("label")
        self.butConfirm = QtWidgets.QPushButton(Order)
        self.butConfirm.setGeometry(QtCore.QRect(250, 370, 131, 31))
        self.butConfirm.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(170, 85, 0);\n"
"color: white;")
        self.butConfirm.setObjectName("butConfirm")
#         self.butBack = QtWidgets.QPushButton(Order)
#         self.butBack.setGeometry(QtCore.QRect(10, 370, 131, 31))
#         self.butBack.setStyleSheet("border-radius: 10px;\n"
# "background-color: rgb(255, 255, 255);\n"
# "color: rgb(170, 85, 0);\n"
# "")
#         self.butBack.setObjectName("butBack")
        self.label_3 = QtWidgets.QLabel(Order)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.label_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 85, 0);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(Order)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 341, 291))
        self.tableWidget.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Order)
        QtCore.QMetaObject.connectSlotsByName(Order)

        self.display(lib_Help.getOrder())
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.butConfirm.clicked.connect(self.printReceipt)
        self.Order = Order
        self.Pizza = Pizza

    def display(self, condition):
        countrow = 0
        horder1 = QtWidgets.QTableWidgetItem("Name")
        horder2 = QtWidgets.QTableWidgetItem("Type")
        horder3 = QtWidgets.QTableWidgetItem("Price")
        horder4 = QtWidgets.QTableWidgetItem("Amount")

        self.tableWidget.setHorizontalHeaderItem(0, horder1)
        self.tableWidget.setHorizontalHeaderItem(1, horder2)
        self.tableWidget.setHorizontalHeaderItem(2, horder3)
        self.tableWidget.setHorizontalHeaderItem(3, horder4)
        for rowdata in condition:
            self.tableWidget.insertRow(countrow)
            countcol = 0
            for data in rowdata.values():
                self.tableWidget.setItem(countrow, countcol, QtWidgets.QTableWidgetItem('{}'.format(data)))
                countcol += 1
            countrow += 1

    def printReceipt(self):
        path = os.getcwd()
        Receipt.createReceipt()
        webbrowser.open_new_tab("{}/receipt/OrderID_{}.html".format(path, lib_Help.getOrderPrint()[0]))
        lib_Help.clearorder()
        self.Pizza.show()
        self.Order.close()

    def retranslateUi(self, Order):
        _translate = QtCore.QCoreApplication.translate
        Order.setWindowTitle(_translate("Order", "Order"))
        self.butConfirm.setText(_translate("Order", "Confirm"))
        # self.butBack.setText(_translate("Order", "Back"))
        self.label_3.setText(_translate("Order", "Order Detail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Order = QtWidgets.QDialog()
    ui = Ui_Order()
    ui.setupUi(Order)
    Order.show()
    sys.exit(app.exec_())
